# Generated by Django 4.2.24 on 2025-10-21 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('sn', models.CharField(max_length=255, unique=True)),
                ('heart_beat_time', models.DateTimeField(auto_now_add=True)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('office', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid', to='office.office')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pilgrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('camera_count', models.IntegerField(blank=True, null=True)),
                ('rfid_count', models.IntegerField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField()),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='counter_image/%Y/%m/%d/')),
                ('illegal_pilgrims', models.IntegerField(default=0)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.office')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('sn', models.CharField(max_length=255, unique=True)),
                ('heart_beat_time', models.DateTimeField(auto_now_add=True)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('office', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera', to='office.office')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
