# Generated by Django 4.2.24 on 2025-11-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
        ('pilgrims', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pilgrim',
            unique_together={('office', 'time_stamp')},
        ),
    ]
