# Generated by Django 4.2.24 on 2025-11-25 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
        ('pilgrims', '0002_alter_pilgrim_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('sn', models.CharField(max_length=255)),
                ('camera_count', models.IntegerField()),
                ('time_stamp', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='counter_image/%Y/%m/%d/')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.office')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFIDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('sn', models.CharField(max_length=255)),
                ('rfid_count', models.IntegerField()),
                ('time_stamp', models.DateTimeField()),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.office')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Pilgrim',
        ),
    ]
