# Generated by Django 4.2.24 on 2025-11-26 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
        ('pilgrims', '0003_cameracounter_rfidcounter_delete_pilgrim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilgrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('camera_count', models.IntegerField(blank=True, null=True)),
                ('rfid_count', models.IntegerField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField()),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='counter_image/%Y/%m/%d/')),
                ('illegal_pilgrims', models.IntegerField(default=0)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.office')),
            ],
            options={
                'unique_together': {('office', 'time_stamp')},
            },
        ),
    ]
