# Generated by Django 4.2.24 on 2025-09-20 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('sn', models.CharField(max_length=255, unique=True)),
                ('heart_beat_time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment'), ('peoplecount', 'peoplecount')], default='guard', max_length=255)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera', to='office.office')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('guard', 'guard'), ('kitchen', 'kitchen'), ('garbage', 'garbage'), ('buffet', 'buffet'), ('bathroom', 'bathroom'), ('sentiment', 'sentiment'), ('peoplecount', 'peoplecount')], max_length=255, unique=True)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_ar', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('sn', models.CharField(max_length=255)),
                ('total_in', models.IntegerField(default=0)),
                ('total_out', models.IntegerField(default=0)),
                ('passby', models.IntegerField(default=0)),
                ('turnback', models.IntegerField(default=0)),
                ('avg_stay_time', models.IntegerField(default=0)),
                ('in_adult', models.IntegerField(default=0)),
                ('out_adult', models.IntegerField(default=0)),
                ('passby_adult', models.IntegerField(default=0)),
                ('turnback_adult', models.IntegerField(default=0)),
                ('in_child', models.IntegerField(default=0)),
                ('out_child', models.IntegerField(default=0)),
                ('passby_child', models.IntegerField(default=0)),
                ('turnback_child', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='counter_image/%Y/%m/%d/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.camera')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
