# Generated by Django 4.2.24 on 2025-09-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_temperature', models.BooleanField(default=False)),
                ('is_guard', models.BooleanField(default=False)),
                ('is_peoplecount', models.BooleanField(default=False)),
                ('is_kitchen', models.BooleanField(default=False)),
                ('is_foodweight', models.BooleanField(default=False)),
                ('is_cleanness', models.BooleanField(default=False)),
                ('is_buffet', models.BooleanField(default=False)),
                ('is_cleaners', models.BooleanField(default=False)),
                ('is_sentiment', models.BooleanField(default=False)),
                ('is_water_tank', models.BooleanField(default=False)),
                ('is_sensor_assign', models.BooleanField(default=False)),
                ('is_annotator_ranking', models.BooleanField(default=False)),
                ('is_settings', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='company_fav_icon/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_temperature', models.BooleanField(default=False)),
                ('is_guard', models.BooleanField(default=False)),
                ('is_peoplecount', models.BooleanField(default=False)),
                ('is_kitchen', models.BooleanField(default=False)),
                ('is_foodweight', models.BooleanField(default=False)),
                ('is_cleanness', models.BooleanField(default=False)),
                ('is_buffet', models.BooleanField(default=False)),
                ('is_cleaners', models.BooleanField(default=False)),
                ('is_sentiment', models.BooleanField(default=False)),
                ('is_water_tank', models.BooleanField(default=False)),
                ('is_sensor_assign', models.BooleanField(default=False)),
                ('is_annotator_ranking', models.BooleanField(default=False)),
                ('is_settings', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_annotator', models.BooleanField(default=False)),
                ('sensor_update_permission', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
