# Generated by Django 4.2.24 on 2025-09-20 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('camera', '0001_initial'),
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='assigned_office',
            field=models.ManyToManyField(blank=True, to='office.office'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='camera_type_annotator',
            field=models.ManyToManyField(blank=True, to='camera.cameratype'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='authentication.company'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='company_annotator',
            field=models.ManyToManyField(blank=True, to='authentication.company'),
        ),
    ]
